### ISSUE TITLE
"Once per exchange" on Marksmanship's Hit the Weak Point

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#8]
Marksmanship's Hit the Weak Point reads, "Once per exchange may invoke a target's consequence (of a physical nature) without spending a fate point."  Each player can only invoke a consequence once per exchange anyway, correct?

**Comment by pjlewis505** [comment]
Yeah, that's correct. I didn't want the stunt to read that you could freely invoke all of a target's consequences. It's also a little bit of defensive writing - since sometimes effects can stack in ways I didn't foresee. But it might not be the most deliberate verbiage. I'll make a note to discuss this.
